/*
	This file uses the header "elbow.h" that uses
	the koolplot library for to plot the graph
	generated by Elbow method.

	Installation of the koolplot library:
		http://koolplot.codecutter.org/

	Libs for the compilation process using the koolplot library:
		lkoolplot, lbgi, lgdi32, lcomdlg32, luuid, loleaut32, lole32

	Elbow method is a heuristic to discover the number of clusters.
	This may or may not work well in particular because is a heuristic!
*/

#include <iostream>
#include <time.h>
#include "elbow.h"
#include "fasta_file.h"

int main()
{
	srand(time(NULL));

	std::string dataset_name("splice.data.600.sequences.fasta");
	FastaFile ff(dataset_name);
	std::vector<std::pair<std::string, std::string> > dataset;

	dataset = ff.getSequences();

	std::vector<std::pair<std::string, std::string> >::iterator it;
	std::vector<std::string> sequences;

	for(it = dataset.begin(); it != dataset.end(); it++)
		sequences.push_back((*it).second);

	Elbow elbow(sequences, "HAMMING", 2, 10);
	elbow.run();

	return 0;
}
